version: 2.1

jobs:
  build:
    docker: 
      - image: cyversevice/ml-tooling
        auth: 
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout


orbs:
  docker: circleci/docker@1.3.0
version: 2.1
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: cyversevice/ml-tooling:light
          auth: 
            username: $DOCKER_LOGIN
            password: $DOCKER_PASSWORD
