# version: 2.1

jobs:
  build:
    - run:
      name: Install Docker client
      command: apk add docker-cli
    docker: 
      - image: cyversevice/ml-workspace:light
    steps:
      - checkout
      - setup_remote_docker: 
          version: 18.06.0-ce
      - run: docker build -t cyversevice/ml-workspace:light .



# orbs:
#   docker: circleci/docker@1.3.0
# version: 2.1
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           image: cyversevice/ml-tooling:light
  
