version: 2.1

jobs:
  build:
    docker: 
      - image: cyversevice/ml-workspace:light
    steps:
      - run:
          name: Install Docker client
          command: apt install docker.io
      - checkout
      - setup_remote_docker
      - run: docker build -t cyversevice/ml-workspace:gpu -f GPU/Dockerfile .
      - run: docker images
      - run: docker run cyversevice/ml-workspace:gpu -h
      - run: docker build -t cyversevice/ml-workspace:light -f light/Dockerfile .
      - run: docker run cyversevice/ml-workspace:light -h
      - run: docker build -t cyversevice/ml-workspace:minimal -f minimal/Dockerfile .
      - run: docker run cyversevice/ml-workspace:minimal -h
      - run: docker build -t cyversevice/ml-workspace:r -f R/Dockerfile .
      - run: docker run cyversevice/ml-workspace:r -h

# orbs:
#   docker: circleci/docker@1.3.0
# version: 2.1
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           image: cyversevice/ml-tooling:light
  
