# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference

# Use a package of configuration called an orb.
# orbs:
#   docker: circleci/docker@1.3.0
# version: 2.1
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           image: cyversevice/ml-workspace:minimal
#       - docker/publish:
#           image: cyversevice/ml-workspace:light
#       - docker/publish:
#           image: cyversevice/ml-workspace:r
#       - docker/publish:
#           image: cyversevice/ml-workspace:gpu

jobs:
  check-and-build-only:
    executor: docker/machine
    steps:
      - checkout
      - docker/check
      - docker/build:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
orbs:
  docker: circleci/docker@1.3.0
version: 2.1
workflows:
  build-docker-image-only:
    jobs:
      - check-and-build-only


    