version: 2.1

jobs:
  build:
    docker: 
      - image: cyversevice/ml-workspace:light
    steps:
      - run:
          name: Install Docker client
          command: apt install docker.io
      - checkout
      - setup_remote_docker
      - run: docker build -t cyversevice/ml-workspace-gpu:0.9.1 -f GPU/Dockerfile .
      - run: docker run -d cyversevice/ml-workspace-gpu:0.9.1
      - run: docker build -t cyversevice/ml-workspace-light:0.9.1 -f light/Dockerfile .
      - run: docker run -d cyversevice/ml-workspace-light:0.9.1
      - run: docker build -t cyversevice/ml-workspace-minimal:0.9.1 -f minimal/Dockerfile .
      - run: docker run -d cyversevice/ml-workspace-minimal:0.9.1
      - run: docker build -t cyversevice/ml-workspace-r:0.9.1 -f R/Dockerfile .
      - run: docker run -d cyversevice/ml-workspace-r:0.9.1