# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference

# Use a package of configuration called an orb.
# orbs:
#   docker: circleci/docker@1.3.0
# version: 2.1
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           image: cyversevice/ml-workspace:minimal
#       - docker/publish:
#           image: cyversevice/ml-workspace:light
#       - docker/publish:
#           image: cyversevice/ml-workspace:r
#       - docker/publish:
#           image: cyversevice/ml-workspace:gpu

version: 2.1
jobs:
  build:
    docker: 
      - image: cyversevice/ml-workspace:minimal # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: dockcer build -t "cyversevice/ml-workspace:minimal .
      
