version: 2.1

jobs:
  build:
    docker: 
      - image: cyversevice/ml-workspace:light
        # auth: 
        #   username: $DOCKER_LOGIN
        #   password: $DOCKER_PASSWORD
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t cyversevice/ml-workspace:light .


# orbs:
#   docker: circleci/docker@1.3.0
# version: 2.1
# auth: 
#   username: $DOCKER_LOGIN
#   password: $DOCKER_PASSWORD
# workflows:
#   build-docker-image-only:
#     jobs:
#       - docker/publish:
#           image: cyversevice/ml-tooling:light
  
