jobs:
  build1:
    docker:
      - image: cyversevice/ml-workspace:minimal
    steps:
      - checkout
      - run: jupyter lab --version
  build2:
    docker:
      - image: cyversevice/ml-workspace:light
    steps:
      - checkout
      - run: jupyter lab --version    
  build3:
    docker:
      - image: cyversevice/ml-workspace:r
    steps:
      - checkout
      - run: jupyter lab --version    
  build4:
    docker:
      - image: cyversevice/jupyterlab-scipy:gpu
      - checkout
      - run: jupyter lab --version    
workflows:
  version: 2
  build1_to_build4:
    jobs:
      - build1
      - build2
      - build3
      - build4
