version: 2.1

jobs:
  build:
    docker: 
      - image: cyversevice/ml-tooling:minimal
        auth: 
          username: $DOCKER_LOGIN
          password: $DOCKER_PASSWORD
    steps:
      - checkout
