version: 2.1

jobs:
  build:
    docker: 
      - image: cyversevice/ml-workspace:light
    steps:
      - run:
          name: Install Docker client
          command: apt install docker.io
      - checkout
      - setup_remote_docker
      - run: docker build -t cyversevice/ml-workspace:gpu -f GPU/Dockerfile .
      - run: docker run -d cyversevice/ml-workspace:gpu
      - run: docker build -t cyversevice/ml-workspace:light -f light/Dockerfile .
      - run: docker run -d cyversevice/ml-workspace:light
      - run: docker build -t cyversevice/ml-workspace:minimal -f minimal/Dockerfile .
      - run: docker run -d cyversevice/ml-workspace:minimal
      - run: docker build -t cyversevice/ml-workspace:r -f R/Dockerfile .
      - run: docker run -d cyversevice/ml-workspace:r