# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference

# Use a package of configuration called an orb.
orbs:
  docker: circleci/docker@1.3.0
version: 2.1
workflows:
  build-docker-image-only:
    jobs:
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
      - docker/publish:
          image: cyversevice/ml-workspace:light
      - docker/publish:
          image: cyversevice/ml-workspace:r
      - docker/publish:
          image: cyversevice/ml-workspace:gpu
